apiVersion: v1
kind: Service
metadata:
  name: ml-inference
  labels:
    app.kubernetes.io/name: ml-inference
    app.kubernetes.io/instance: plain-k8s
    app.kubernetes.io/part-of: argo-ml-workloads
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ml-inference
    app.kubernetes.io/instance: plain-k8s
  ports:
    - name: http
      port: 80
      targetPort: http

