apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-inference-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sammaher1/argo-ml-workloads.git
    targetRevision: main
    path: workloads/k8s
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-lab-k8s
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
